name: Build & Push image to GHCR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # （可选）若你的 ClawCloud 工作区启用了 API/Webhook，可放开以下步骤实现自动滚动更新
      # - name: Trigger ClawCloud redeploy (optional)
      #   run: |
      #     curl -fsS -X POST "$CLAW_API_BASE/apps/$CLAW_APP_ID/deploy" \
      #       -H "Authorization: Bearer $CLAW_API_TOKEN" \
      #       -H "Content-Type: application/json" \
      #       -d '{"image":"ghcr.io/'"${{ github.repository }}"':main"}'
      #   env:
      #     CLAW_API_BASE: ${{ secrets.CLAW_API_BASE }}
      #     CLAW_APP_ID: ${{ secrets.CLAW_APP_ID }}
      #     CLAW_API_TOKEN: ${{ secrets.CLAW_API_TOKEN }}
